apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
            environment: test
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: nginx
                environment: test
        spec:
            containers:
            - name: nginx
              image: nginx
              ports:
              - containerPort: 80
                
    
