kind: Pod
apiVersion: v1
metadata:
  name: pod-env-var
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx-server
      image: nginx
      ports:
      - containerPort: 80
        hostPort: 80
      
