apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name : my-first-pvc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: standard
    resources:
        requests:
            storage: 6Gi
