apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        app: mysql
    name: pvc
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: gp2-retain
    volumeMode: Filesystem
    volumeName: pv
