apiVersion: v1
kind: ResourceQuota
metadata:
    name: my-new-esource-resourcequota
    namespace:  my-new-ns
spec:
    hard:
        requests.cpu: "1"
        requests.memory: 1Gi
        limits.cpu: "2"
        limits.memory: 2Gi

