apiVersion: v1
kind: Service
metadata:
    name: my-nginx-app-service
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: nginx
        
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name : my-ingress
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        kubernetes.io/ingress.class: alb
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
                name: my-nginx-app-service
                port:
                    number: 80


